package com.example.horry.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.horry.greendao.GreenNews;
import com.example.horry.greendao.GreenStat;
import com.example.horry.greendao.GreenTop;
import com.example.horry.greendao.GreenIndex;
import com.example.horry.greendao.GreenItem;
import com.example.horry.greendao.GreenLeague;
import com.example.horry.greendao.GreenVideo;

import com.example.horry.greendao.GreenNewsDao;
import com.example.horry.greendao.GreenStatDao;
import com.example.horry.greendao.GreenTopDao;
import com.example.horry.greendao.GreenIndexDao;
import com.example.horry.greendao.GreenItemDao;
import com.example.horry.greendao.GreenLeagueDao;
import com.example.horry.greendao.GreenVideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenNewsDaoConfig;
    private final DaoConfig greenStatDaoConfig;
    private final DaoConfig greenTopDaoConfig;
    private final DaoConfig greenIndexDaoConfig;
    private final DaoConfig greenItemDaoConfig;
    private final DaoConfig greenLeagueDaoConfig;
    private final DaoConfig greenVideoDaoConfig;

    private final GreenNewsDao greenNewsDao;
    private final GreenStatDao greenStatDao;
    private final GreenTopDao greenTopDao;
    private final GreenIndexDao greenIndexDao;
    private final GreenItemDao greenItemDao;
    private final GreenLeagueDao greenLeagueDao;
    private final GreenVideoDao greenVideoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenNewsDaoConfig = daoConfigMap.get(GreenNewsDao.class).clone();
        greenNewsDaoConfig.initIdentityScope(type);

        greenStatDaoConfig = daoConfigMap.get(GreenStatDao.class).clone();
        greenStatDaoConfig.initIdentityScope(type);

        greenTopDaoConfig = daoConfigMap.get(GreenTopDao.class).clone();
        greenTopDaoConfig.initIdentityScope(type);

        greenIndexDaoConfig = daoConfigMap.get(GreenIndexDao.class).clone();
        greenIndexDaoConfig.initIdentityScope(type);

        greenItemDaoConfig = daoConfigMap.get(GreenItemDao.class).clone();
        greenItemDaoConfig.initIdentityScope(type);

        greenLeagueDaoConfig = daoConfigMap.get(GreenLeagueDao.class).clone();
        greenLeagueDaoConfig.initIdentityScope(type);

        greenVideoDaoConfig = daoConfigMap.get(GreenVideoDao.class).clone();
        greenVideoDaoConfig.initIdentityScope(type);

        greenNewsDao = new GreenNewsDao(greenNewsDaoConfig, this);
        greenStatDao = new GreenStatDao(greenStatDaoConfig, this);
        greenTopDao = new GreenTopDao(greenTopDaoConfig, this);
        greenIndexDao = new GreenIndexDao(greenIndexDaoConfig, this);
        greenItemDao = new GreenItemDao(greenItemDaoConfig, this);
        greenLeagueDao = new GreenLeagueDao(greenLeagueDaoConfig, this);
        greenVideoDao = new GreenVideoDao(greenVideoDaoConfig, this);

        registerDao(GreenNews.class, greenNewsDao);
        registerDao(GreenStat.class, greenStatDao);
        registerDao(GreenTop.class, greenTopDao);
        registerDao(GreenIndex.class, greenIndexDao);
        registerDao(GreenItem.class, greenItemDao);
        registerDao(GreenLeague.class, greenLeagueDao);
        registerDao(GreenVideo.class, greenVideoDao);
    }
    
    public void clear() {
        greenNewsDaoConfig.getIdentityScope().clear();
        greenStatDaoConfig.getIdentityScope().clear();
        greenTopDaoConfig.getIdentityScope().clear();
        greenIndexDaoConfig.getIdentityScope().clear();
        greenItemDaoConfig.getIdentityScope().clear();
        greenLeagueDaoConfig.getIdentityScope().clear();
        greenVideoDaoConfig.getIdentityScope().clear();
    }

    public GreenNewsDao getGreenNewsDao() {
        return greenNewsDao;
    }

    public GreenStatDao getGreenStatDao() {
        return greenStatDao;
    }

    public GreenTopDao getGreenTopDao() {
        return greenTopDao;
    }

    public GreenIndexDao getGreenIndexDao() {
        return greenIndexDao;
    }

    public GreenItemDao getGreenItemDao() {
        return greenItemDao;
    }

    public GreenLeagueDao getGreenLeagueDao() {
        return greenLeagueDao;
    }

    public GreenVideoDao getGreenVideoDao() {
        return greenVideoDao;
    }

}
