package com.example.horry.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_LEAGUE".
 */
public class GreenLeague {

    private Long id;
    private String leagueentity;
    private String kinds;

    public GreenLeague() {
    }

    public GreenLeague(Long id) {
        this.id = id;
    }

    public GreenLeague(Long id, String leagueentity, String kinds) {
        this.id = id;
        this.leagueentity = leagueentity;
        this.kinds = kinds;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLeagueentity() {
        return leagueentity;
    }

    public void setLeagueentity(String leagueentity) {
        this.leagueentity = leagueentity;
    }

    public String getKinds() {
        return kinds;
    }

    public void setKinds(String kinds) {
        this.kinds = kinds;
    }

}
