package com.example.horry.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.horry.greendao.GreenLeague;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_LEAGUE".
*/
public class GreenLeagueDao extends AbstractDao<GreenLeague, Long> {

    public static final String TABLENAME = "GREEN_LEAGUE";

    /**
     * Properties of entity GreenLeague.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Leagueentity = new Property(1, String.class, "leagueentity", false, "LEAGUEENTITY");
        public final static Property Kinds = new Property(2, String.class, "kinds", false, "KINDS");
    };


    public GreenLeagueDao(DaoConfig config) {
        super(config);
    }
    
    public GreenLeagueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_LEAGUE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LEAGUEENTITY\" TEXT," + // 1: leagueentity
                "\"KINDS\" TEXT);"); // 2: kinds
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_LEAGUE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GreenLeague entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String leagueentity = entity.getLeagueentity();
        if (leagueentity != null) {
            stmt.bindString(2, leagueentity);
        }
 
        String kinds = entity.getKinds();
        if (kinds != null) {
            stmt.bindString(3, kinds);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GreenLeague readEntity(Cursor cursor, int offset) {
        GreenLeague entity = new GreenLeague( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // leagueentity
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // kinds
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GreenLeague entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLeagueentity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKinds(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GreenLeague entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GreenLeague entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
