package com.example.horry.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_ITEM".
 */
public class GreenItem {

    private Long id;
    private String itementity;
    private String Ids;

    public GreenItem() {
    }

    public GreenItem(Long id) {
        this.id = id;
    }

    public GreenItem(Long id, String itementity, String Ids) {
        this.id = id;
        this.itementity = itementity;
        this.Ids = Ids;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getItementity() {
        return itementity;
    }

    public void setItementity(String itementity) {
        this.itementity = itementity;
    }

    public String getIds() {
        return Ids;
    }

    public void setIds(String Ids) {
        this.Ids = Ids;
    }

}
