package com.example.horry.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_VIDEO".
 */
public class GreenVideo {

    private Long id;
    private String videoentity;
    private String kindtype;

    public GreenVideo() {
    }

    public GreenVideo(Long id) {
        this.id = id;
    }

    public GreenVideo(Long id, String videoentity, String kindtype) {
        this.id = id;
        this.videoentity = videoentity;
        this.kindtype = kindtype;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVideoentity() {
        return videoentity;
    }

    public void setVideoentity(String videoentity) {
        this.videoentity = videoentity;
    }

    public String getKindtype() {
        return kindtype;
    }

    public void setKindtype(String kindtype) {
        this.kindtype = kindtype;
    }

}
