package com.example.horry.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_INDEX".
 */
public class GreenIndex {

    private Long id;
    private String indexentity;
    private String typevalue;

    public GreenIndex() {
    }

    public GreenIndex(Long id) {
        this.id = id;
    }

    public GreenIndex(Long id, String indexentity, String typevalue) {
        this.id = id;
        this.indexentity = indexentity;
        this.typevalue = typevalue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIndexentity() {
        return indexentity;
    }

    public void setIndexentity(String indexentity) {
        this.indexentity = indexentity;
    }

    public String getTypevalue() {
        return typevalue;
    }

    public void setTypevalue(String typevalue) {
        this.typevalue = typevalue;
    }

}
