package com.example.horry.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.horry.greendao.GreenTop;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_TOP".
*/
public class GreenTopDao extends AbstractDao<GreenTop, Long> {

    public static final String TABLENAME = "GREEN_TOP";

    /**
     * Properties of entity GreenTop.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Topentity = new Property(1, String.class, "topentity", false, "TOPENTITY");
        public final static Property Typekind = new Property(2, String.class, "typekind", false, "TYPEKIND");
    };


    public GreenTopDao(DaoConfig config) {
        super(config);
    }
    
    public GreenTopDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_TOP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TOPENTITY\" TEXT," + // 1: topentity
                "\"TYPEKIND\" TEXT);"); // 2: typekind
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_TOP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GreenTop entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String topentity = entity.getTopentity();
        if (topentity != null) {
            stmt.bindString(2, topentity);
        }
 
        String typekind = entity.getTypekind();
        if (typekind != null) {
            stmt.bindString(3, typekind);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GreenTop readEntity(Cursor cursor, int offset) {
        GreenTop entity = new GreenTop( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // topentity
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // typekind
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GreenTop entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTopentity(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTypekind(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GreenTop entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GreenTop entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
